title: "Matthew Chuang"
name: "Matthew Chuang"
description: "Personal blog"
url: "https://mattioch.github.io"
baseurl: ""

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
